### PR TITLE
#786 Added viewport configuration options to the Chromium screenshot API route

### PR DESCRIPTION
**Pull request by gg-gaborginter**
@gulien I imagined something like this. I'm also willing to update the corresponding sections of the documentation page, if necessary.

### CODE REVIEW

**Review by frostmark — APPROVED** [review]

**Comment by gulien** [comment]
@frostmark make yourself at home, mate.

@gg-gaborginter could you provide me samples (screenshots) using different viewport?

**Comment by gg-gaborginter** [comment]
@frostmark I'm providing the asked screenshots by the end of this week, if that's still fine.

**Comment by gg-gaborginter** [comment]
Tested the following setups:
1. Default behaviour, no custom viewport settings, the capture beyond viewport flag left untouched (in 8.0.2, always true). The default viewport is 800x600, and so the resulting image size is 800x2208 pixels. 
`curl --request POST http://localhost:3000/forms/chromium/screenshot/url --form url=https://gotenberg.dev/docs/getting-started/introduction --form format=jpeg --form quality=100 --form optimizeForSpeed=true -o web_page_no_custom_viewport.jpeg`
web_page_no_custom_viewport

2. Custom viewport is set (640x480 pixels), the capture beyond viewport flag left untouched. The viewport is changed to 640x480, and the resulting image is 640x2208 pixels.
`curl --request POST http://localhost:3000/forms/chromium/screenshot/url --form url=https://gotenberg.dev/docs/getting-started/introduction --form format=jpeg --form quality=100 --form optimizeForSpeed=true --form captureBeyondViewport=true --form viewportWidth=640 --form viewportHeight=480 -o web_page_custom_viewport_capture_beyond_viewport.jpeg`
web_page_custom_viewport_capture_beyond_viewport

3. Custom viewport is set (640x480 pixels), the capture beyond viewport flag is set to `false`. The viewport is changed to 640x480, and the resulting image is finally the desired 640x480 pixels.
`curl --request POST http://localhost:3000/forms/chromium/screenshot/url --form url=https://gotenberg.dev/docs/getting-started/introduction --form format=jpeg --form quality=100 --form optimizeForSpeed=true --form captureBeyondViewport=false --form viewportWidth=640 --form viewportHeight=480 -o web_page_custom_viewport_capture_only_viewport.jpeg`
web_page_custom_viewport_capture_only_viewport

**Comment by gulien** [comment]
@gg-gaborginter thanks a lot for the effort!

So it looks like it works properly for viewports <= `800x600`. During my experiments, it started to go wrong for bigger viewports though. I'm really not familiar with potential uses case, but I anticipated users reporting "issues" and that's why I ditched this functionality completely.

Does it make sense to request bigger viewports? Because in such scenarios, the screenshot displays additional background to the right 🤔

**Comment by gg-gaborginter** [comment]
@gulien You are right here, I was focusing on smaller resolutions only. Let me test larger ones, as well, and I'll share my findings.

**Comment by gulien** [comment]
Hey,

Closing this in favor of #816, which seems to be the way to go.

**Comment by gg-gaborginter** [comment]
Okay, for full closure, the screenshots, I owed you @gulien.

In the PR there are 2 commits. The first one is only limiting the viewport of the screenshot. With this approach, having a larger viewport than the default window (rendering viewport) size (800x600) will result in the content aligned to the left and blank spaces on the right and the bottom.

The second one changes the implementation to the presumably correct approach:
1. it opens a window (browser page) of the desired size (rendering viewport), then
2. opens the page and
3. it limits the size (viewport) of the screenshot.
The screenshots in the earlier round were made already with the corrected implementation. In this case, having larger viewports (identical for both rendering and the screenshot), will result in fullscreen images, no blank spaces around, unless the page has a width limit defined in CSS. Then the page will be aligned in the middle of the screenshot.

**Comment by gg-gaborginter** [comment]
web_page_custom_viewport_capture_beyond_viewport_large_resolution_with_window_resize
web_page_custom_viewport_capture_within_viewport_large_resolution_with_window_resize
web_page_custom_viewport_capture_within_viewport_large_resolution_with_screenshot_viewport_only
web_page_custom_viewport_capture_beyond_viewport_large_resolution_with_screenshot_resize_only

**Pull request closed without merging**
