### PR TITLE
feat(libreoffice): retry on core dumped

### LINKED ISSUE #639: unoconv PDF: unix process error: wait for unix process: signal: segmentation fault (core dumped)
Seemingly LibreOffice segfaults - not sure if that's anything that can be rescued by gotenberg itself. I guess it's just another instability of LO itself?

```json
{
   "level":"error",
   "ts":1682589868.6889822,
   "logger":"api",
   "msg":"convert HTML to PDF: convert PDF: convert PDF to 'PDF/A-1a' with multi PDF engines: convert PDF to 'PDF/A-1a' with PDFcpu: method not available; convert PDF to 'PDF/A-1a' with PDFtk: method not available; convert PDF to 'PDF/A-1a' with QPDF: method not available; convert PDF to 'PDF/A-1a' with unoconv: unoconv PDF: unix process error: wait for unix process: signal: segmentation fault (core dumped)",
   "trace":"deb4a7ef-184a-4f80-bbe1-f2654d310b25",
   "remote_ip":"172.20.0.88",
   "host":"converter:3000",
   "uri":"/forms/chromium/convert/html",
   "method":"POST",
   "path":"/forms/chromium/convert/html",
   "referer":"",
   "user_agent":"ReactorNetty/1.0.17",
   "status":500,
   "latency":1898941311,
   "latency_human":"1.898941311s",
   "bytes_in":-1,
   "bytes_out":21
}
```
The image used is `gotenberg/gotenberg:7.7.2`

### PR DESCRIPTION
**Pull request by gulien**
Closes #639.

### CODE REVIEW

**Comment by gulien** [comment]
@giamma @PierreSchwang @pieterocp 

The image `gulnap/gotenberg:retry-core-dumped` is available for testing. It provides an auto retry in case of *core dumped* error. Do not hesitate to provide some feedbacks so that I can merge this PR! 😄

**Comment by giamma** [comment]
Thank you, I'll try to provide feedback as soon as possible.

**Comment by giamma** [comment]
Hi, here is my feedback. We ran some load tests for several hours using the new experimental image.

We did not experience any error at the application level related to the segfault, so I would say that that problem is gone. I cannot be 100% sure because the issue was stochastic, but on the other hand we ran the tests for several hours, and in the past this was sufficient to trigger the problem at least once. The change also seems to be perfectly backward compatible. 

However, on a second run we experienced one conversion failure which produced the following log on gotenberg, as you can see it's not related to segmentation fault. Again, it does not depend on the document, the load tests uses the same document for all requests.

`
{"level":"error","ts":1721632727.3638284,"logger":"api","msg":"convert to PDF: convert to PDF: unix process error: wait for unix process: exit status 1","trace":"b2dfdfce-a780-4c13-8125-c0b4bf53e2fe","remote_ip":"10.252.4.80","host":"gotenberg.performance:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"Apache-HttpClient/4.5.14 (Java/17.0.11)","status":500,"latency":4686745239,"latency_human":"4.686745239s","bytes_in":206305,"bytes_out":21}
`

**Comment by gulien** [comment]
Thanks for the feedback! 

> convert to PDF: convert to PDF: unix process error: wait for unix process: exit status 1

Looks like LibreOffice crashed in this instance, while the core dumped is more a "try catch" event.

**Comment by gulien** [comment]
@giamma `gotenberg:gotenberg:edge` should be available within ~1 hour 😉

**Pull request merged**
