### PR TITLE
fix: special characters issues with filenames

### LINKED ISSUE #662: Nordic characters break loading
Tried to convert a html to pdf, but got a issue when the attachment has characters like `äåö`

This was the html:

```html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <style>
        .center {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 100%;
        }
    </style>
</head>

<body>
	<img src="Ska%cc%88rmavbild%202023-07-18%20kl.%2012.13.23.png" class="center">
	<img src="test.png" class="center">
</body>

</html>
```

Using this command:

```bash
curl \
--request POST 'http://localhost:3000/forms/chromium/convert/html' \
--form 'files=@"index.html"' \
--form 'files=@"test.png"' \
--form 'files=@"Skärmavbild 2023-07-18 kl. 12.13.23.png"' \
-o my.pdf
```

The output was a failed image on the first, and correct one on second.  Both pngs are same content

### LINKED ISSUE #730: Error when converting xls file with german special character ß in file name
Gotenberg conversion fails when file name contains German special character ß.

Test file has the name `Special_Chars_ß.xlsx`.

Used curl to upload the file:
`curl --request POST --url http://127.0.01:3000/forms/libreoffice/convert --header 'Content-Type: multipart/form-data' --form files=@'Special_Chars_ß.xlsx' -o result.pdf`

This leads to the following error:
`{"level":"error","ts":1701360920.8984268,"logger":"api","msg":"convert to PDF: convert to PDF: unix process error: wait for unix process: exit status 6","trace":"2a1e60d7-745c-474c-a444-2ef7a0a30c74","remote_ip":"192.168.65.1","host":"127.0.0.1:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"curl/8.1.2","status":500,"latency":57993208,"latency_human":"57.993208ms","bytes_in":8946,"bytes_out":21}`

[Special_Chars_ß.xlsx](https://github.com/gotenberg/gotenberg/files/13515174/Special_Chars_ss.xlsx)

### PR DESCRIPTION
**Pull request by gulien**
Fixes #662 
Fixes #730

### CODE REVIEW

**Comment by hueidou** [comment]
If the file name is irrelevant to subsequent processing, I think it would be more appropriate for Gotenberg to replace the file name with basic Latin characters, such as file.{fileExtension}. This would prevent potential unexpected errors in higher-level applications.

**Comment by gulien** [comment]
Hello @hueidou,

Do you encounter issues with the implementation from this PR? The issue is, AFAIK, only with LibreOffice.

**Comment by hueidou** [comment]
Hi @gulien,

My previous suggestion may not be accurate. I have conducted further tests.

I deployed `docker.io/gotenberg/gotenberg:8.2.1`, when passing a file with an Chinese filename using the command `curl --request POST http://localhost:30627/forms/libreoffice/convert --form files=@/root/中文文件名.docx`, I receive response `Internal Server Error`, server side log:
```plaintext
{"level":"warn","ts":1710948084.0302327,"logger":"api.formslibreofficeconvert","msg":"non-basic latin characters in filename, copy to a file with a valid filename","trace":"afa6c764-6b47-42aa-aee0-adc213ae6e28"}
{"level":"error","ts":1710948084.851542,"logger":"api","msg":"convert to PDF: convert to PDF: unix process error: wait for unix process: exit status 5","trace":"afa6c764-6b47-42aa-aee0-adc213ae6e28","remote_ip":"10.42.0.1","host":"localhost:30627","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"curl/8.2.1","status":500,"latency":823388655,"latency_human":"823.388655ms","bytes_in":20384,"bytes_out":21}
```
when passing an English filename works fine. 

Then I tried `docker.io/gotenberg/gotenberg:8.0.0`, and both Chinese and English filenames work fine.

**Comment by gulien** [comment]
Could you try with `8.2.2`?

**Comment by hueidou** [comment]
> Could you try with `8.2.2`?

I tried `docker.io/gotenberg/gotenberg:8.2.2` works fine.

I noticed this issue occurred in #427, and `8.0.0` also works fine. I am puzzled whether this issue was resolved in 8.2.2 or if it is due to other compilation or build issues.

**Comment by gulien** [comment]
Yes I think the issue is occurring since 8.10, but I’ve fixed an issue in 8.2.2 that was likely causing your 500

**Pull request merged**
