### PR TITLE
feat(libreoffice): add macOS *.pages support

### LINKED ISSUE #635: macOS '*.pages' conversion
Apologies if this was raised in the past, I see that pages is not supported, what would it take to add such support?

Invalid form data: no form file found for extensions: [.bib .doc .xml .docx .fodt .html .ltx .txt .odt .ott .pdb .pdf .psw .rtf .sdw .stw .sxw .uot .vor .wps .epub .png .bmp .emf .eps .fodg .gif .jpg .jpeg .met .odd .otg .pbm .pct .pgm .ppm .ras .std .svg .svm .swf .sxd .sxw .tif .tiff .xhtml .xpm .odp .fodp .potm .pot .pptx .pps .ppt .pwp .sda .sdd .sti .sxi .uop .wmf .csv .dbf .dif .fods .ods .ots .pxl .sdc .slk .stc .sxc .uos .xls .xlt .xlsx]

I am refering to the output file of https://www.apple.com/pages/

### PR DESCRIPTION
**Pull request by gulien**
Closes #635.

### CODE REVIEW

**Comment by eMerzh** [comment]
Hey 👋  

saw this, and it seems interesting, but I noticed it doesn't support "key"(notes) files is there a reason or a plan about that?

**Comment by gulien** [comment]
Hello @eMerzh 👋 what’s a « key »?

**Comment by eMerzh** [comment]
keynotes (apple's powerpoint)

**Comment by gulien** [comment]
It’s mostly a file extension to add, plus some testing to check if LibreOffice is able to handle such files.

**Pull request merged**
