### PR TITLE
feat(libreoffice): add macOS *.key support

### PR DESCRIPTION
**Pull request by eMerzh**
this should work as expected... , to relate to #812

### CODE REVIEW

**Comment by gulien** [comment]
Thanks @eMerzh! Were you able to test it?

**Comment by eMerzh** [comment]
no 🙈... but i mean... it work in libreoffice to open keyfile, so i don't see why it would fail 🤔

**Comment by gulien** [comment]
@eMerzh yeah me neither ^^ but better safe than sorry. Just try to convert it to PDF from LibreOffice directly and if it works I’ll merge your PR 😄

**Comment by eMerzh** [comment]
ok ok :p i had to figure out how to run it :p 

but yeah it got my pdf back 👌  it works here

**Comment by gulien** [comment]
Thanks!

**Pull request merged**
