### PR TITLE
feat(chromium): add ability to export images

### PR DESCRIPTION
**Pull request by andreamouraud**
Hi, this PR implements https://github.com/gotenberg/gotenberg/issues/110

First time using go, hope the code is clear enough, didn't add any test though

## How
- Based on a `format` parameter:
  - `pdf`: default if not specified
  - `img`: exports a `png` if `quality` parameter is 100 (default), otherwise a `jpeg`

## Example
```
curl --request POST 'http://localhost:3000/forms/chromium/convert/url' \
--form 'url="https://www.google.com"' --form 'landscape="true"' --form 'marginTop="1"' \
--form 'marginBottom="1"' --form 'format="img"' -o my.png
```

Thank you for the work on gotenberg !

### CODE REVIEW

**Comment by gulien** [comment]
Hello @andreamouraud,

Thanks for this well written PR. I do not have much time to work on Gotenberg with a young kid at home, so no ETA on a review 😅.

**Comment by DavidBadura** [comment]
Gotenberg is really amazing and solves so many problems for us. Only this feature is missing to make it perfect for us. Thanks for that!

**Comment by andreamouraud** [comment]
Hi @gulien, any update on this? 
I'm willing to provide further help if needed !

**Comment by gulien** [comment]
Hello @andreamouraud,

Sorry for the delay; it's still on my TODO list, but no ETA yet. In the mean time, I strongly suggest creating your own Docker image, using the [template-repository](https://github.com/gotenberg/gotenberg-template-repository) (see for instance https://github.com/Vrex123/gotenberg-ghostscript) or else.

**Comment by ConradKurth** [comment]
@gulien is there anything preventing this PR from being merged? Or is there something I can do to help move this along since it would be great to have this feature in the main branch

**Comment by gulien** [comment]
👋 sorry for the delay, but I'm currently working on this feature for the release of Gotenberg 8.

**Comment by gulien** [comment]
End of the year or january, depending on my available free time.

**Comment by gulien** [comment]
Closing this in favor of #765.

**Pull request closed without merging**
