### PR TITLE
Replace Debian with Ubuntu for greater control over LibreOffice versions

### PR DESCRIPTION
**Pull request by padpadthai**
Hi there,

I noticed the [issues](https://github.com/gotenberg/gotenberg/issues/576) caused by Debian's LibreOffice dependencies. By using Ubuntu Focal you get LibreOffice 7.3.7 which seems more stable than 7.4.x for PDF conversion.

In addition, you can also access more old LibreOffice versions from Ubuntu in the future via [Personal Package Archives](https://launchpad.net/~libreoffice/+archive/ubuntu/ppa) should regressions occur.

Let me know what you think.

### CODE REVIEW

**Comment by gulien** [comment]
Thanks @padpadthai!

I did use Ubuntu previously, but, last time I've checked, recent Chromium versions were only available through the Snap package manager. I did not find a way to use this package manager in a Dockerfile, so I switched to Debian instead.

**Comment by padpadthai** [comment]
Ok thanks for the info @gulien, I think I understand the nuance of the situation now.

Please have a look at the updated commit. It installs Chromium from Debian sources. I used the following sources as guidance for this approach:

- https://askubuntu.com/questions/1204571/how-to-install-chromium-without-snap/1206153#1206153
- https://askubuntu.com/questions/1179273/how-to-remove-snap-completely-without-losing-the-chromium-browser/1206502#1206502
- https://gist.github.com/ishad0w/7665cde882aa7dc3eec99613802e61e4

Would this work?

**Comment by gulien** [comment]
I guess it would work, but it feels a bit hacky IMO 😄 also, @sharongut found out that the culprit could be the garbage collector from Gotenberg (see https://github.com/gotenberg/gotenberg/issues/442#issuecomment-1384186104). I'd prefer for now to look at this direction 😉

**Comment by padpadthai** [comment]
Ok, I agree that the hacky-ness is not ideal here 😅. All the standard approaches I tried were blocked one way or another. Hopefully, you get this resolved via the garbage collector approach.

I will close this PR. Thanks for your feedback 😄

**Comment by gulien** [comment]
Thanks for your time @padpadthai 😄

**Pull request closed without merging**
